### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/ricky/codespace/FolkScope/data/amazon_title_category.txt'

### ISSUE THREAD

**Issue by qige96** [HKUST-KnowComp/FolkScope#4]
Running the script [adapted in this way](https://github.com/HKUST-KnowComp/FolkScope/issues/2), reported such error:
```shell
(transformers) ricky@myremote:~/codespace/FolkScope$ bash scripts/run_generation.sh
Sampling data from source metadata
Traceback (most recent call last):
  File "src/generator/generation.py", line 259, in <module>
    main()
  File "src/generator/generation.py", line 158, in main
    metainfo = get_item_metainfo(args.data_dir + "/amazon_title_category.txt")
  File "/home/ricky/codespace/FolkScope/src/generator/utils.py", line 62, in get_item_metainfo
    infile = open(metafile)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ricky/codespace/FolkScope/data/amazon_title_category.txt'
```
I did not find the data file `amazon_title_category.txt` in your [released dataset](https://hkustconnect-my.sharepoint.com/:f:/g/personal/cyuaq_connect_ust_hk/EhLWuDJtP5pPgPH27i5Oq1oBxfc0wDIqFxpvJhdPcdt9hA?e=6JROlg), could you please add the data to the shared folder (or point me to the file it is already there) ?

**Comment by ccclyu** [comment]
Updated in the shared folder `product_metadata/amazon_title_category.txt`
