### ISSUE TITLE
More data needed

### ISSUE THREAD

**Issue by qige96** [HKUST-KnowComp/FolkScope#5]
from [generator.py](https://github.com/HKUST-KnowComp/FolkScope/blob/main/src/generator/generation.py#L163), `amazon_cobuy_graph.txt` is needed.

from [run_NCF.py](https://github.com/HKUST-KnowComp/FolkScope/blob/main/src/recommendation/run_NCF.py#L90), various `.pickle` files are needed, and I see no way to produce these files by my self. 

I think without these files, I cannot reproduce your experiments.

**Comment by MighTy-Weaver** [comment]
Hi, thanks for your enquiry.

We have uploaded `amazon_cobuy_graph.txt` to our shared Onedrive folder, under the `product_metadata` directory.

The `pickle` files for recommendation can be found in [here](https://hkustconnect-my.sharepoint.com/:f:/g/personal/jbai_connect_ust_hk/EqqnjNof5B1Ot682jWI-XWgBEpXiroLgRs9BwRUTcXyDug?e=KL4ESr), as shown in the [README](https://github.com/HKUST-KnowComp/FolkScope/blob/main/src/recommendation/readme.md?plain=1#L6).
