### ISSUE TITLE
role of abstract intentions in final knowledge graph

### ISSUE THREAD

**Issue by hoangnv735** [HKUST-KnowComp/FolkScope#7]
Thank you for your interesting work. I recently read your paper wanted to express my appreciation for your excellent ideas. However, there are some points that I am still confused.

The script for conceptualization seems confused to me as it refer to `pattern_match.py` and some params are not recognized.
https://github.com/HKUST-KnowComp/FolkScope/blob/9aa37e951687051fe5b28153394e49506821e61f/scripts/run_conceptualization.sh#LL14C1-L22C5

I extracted data from final cleaned gpickle and found the graph has edges like:
`item_id_1-item_id_2, relation, text`
I not sure about the role of abstract intentions in the graph. Are abtract intentions considered as `text` as in above structure, or they are different nodes as you illustrated in [the figure](https://github.com/HKUST-KnowComp/FolkScope/blob/main/figure/folkscope.png)

Could you please give some detail or code about how to aggregate final cleaned data from populated data and patterns.

**Comment by seanliu96** [comment]
Hi Hoang, thanks for your questions. I do not understand the meaning of params that are not recognized. Could you please explain this more clearly, or put some results or errors for discussion? 

For the intentions, I think the text corresponds to the generation/assertion from the language model (e.g., skiing product), and we hope to aggregate such detailed assertions into abstract ones (e.g., outdoor activity product), which refers to the conceptualization process. For the detailed cases illustrated in the figure, I am afraid not of telling an accurate answer because I did not attend to the annotation process. Maybe @ccclyu  can help.

**Comment by seanliu96** [comment]
Oh, I think there is a mistake in run_conceptualization.sh, where the py file should be "python src/pattern/conceptualizer.py "

**Comment by hoangnv735** [comment]
Thank you for your replies. I managed to run the conceptualization scripts after changing the path that you suggested.

Regarding the abstract intentions, I just want to make sure that I understand your method correctly. Here is what I currently understand:
Let's say I have an example generated by LLM (formatted as an edge in the knowledge graph): ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his daughter', {'usedFor': 0.98975}).
The assertion "they could be used for his daughter" is conceptualized to generate three abstract intentions: "they could be used for his offspring," "they could be used for his relative," and "they could be used for his family member." Then, I will add three corresponding edges to the KG:

    ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his offspring', {'usedFor': 0.98975})
    ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his relative', {'usedFor': 0.98975})
    ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his family member', {'usedFor': 0.98975})

Please correct me if the above process is not what your method does.

I think your method follows this approach because when I extracted the .gpickle file (e.g., Electronics_05_05__filtered_kg.gpickle used in the recommendation process), all I have are edges with the same structure as ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his daughter', {'usedFor': 0.98975}). In this structure, I believe that 'B00AWRUIY4-B016XBGWAQ' and 'they could be used for his daughter' are two types of nodes, and {'usedFor': 0.98975} represents the edge.

However, in your paper, the knowledge graph is illustrated as shown in [this figure](https://github.com/HKUST-KnowComp/FolkScope/blob/main/figure/folkscope.png). I infer from this figure that the knowledge graph has three types of nodes (cobuy node, intention node, and abstract intention node) and two types of edges (relation edge and conceptualization edge).

Could you please provide further clarification or explanation so that I can better understand and address your concern. Thank you.

**Comment by seanliu96** [comment]
Usually, the example ('B00AWRUIY4-B016XBGWAQ', 'they could be used for his daughter', {'usedFor': 0.98975}) holds for the intention explanation for the pair of "B00AWRUIY4" and "B016XBGWAQ". Therefore, it is hard to say cobuy is a node. Actually, there is an hyperedge among "B00AWRUIY4", "B016XBGWAQ", and "they could be used for his daughter", which consists of three nodes, and the edge represents the "usedFor" relation, with a weight 0.98975.

As for the upper level, "they could be used for his daughter" is further conceptualized as "they could be used for his family member" without considering the items "B00AWRUIY4" and "B016XBGWAQ". Therefore, "they could be used for his family member" is independent of items. We do not regard the intentions before conceptualization and after conceptualization as the same type of nodes.

I hope that my explanation can address your problem. And welcome to further questions.
